name: 04 - Using Actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        # working-directory: 04-using-actions/react-app # use defaults above
      - name: Run Unit Tests
        run: nmp run test
        # working-directory: 04-using-actions/react-app  # use defaults above