name: 05 - 2 - Event Filters and Activity Types
run-name: "It's a learning workflow run by ${{github.action}}"
on: workflow_dispatch
  # pull_request:
  #   types: [opened, synchronize]
  #   branches:
  #     - main
  #     - solution
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opened or synchronized AND base branch is main."
    
