name: 05 - 1 - Event Filters and Activity Types
run-name: It's a learning workflow run by ${{github.actor}}
on: 
  pull_request:
    types: closed
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is closed"
    
