name: 11 - Working with Inputs
run-name: It's a learning workflow run by ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "Skip deployment and only print build output"
        default: false
      target:
        type: environment
        description: "Which environment the workflow will target"
      tag:
        type: choice
        options:
            - v1
            - v2
            - v3
        default: v3
        description: "Release from which to build and deploy"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Building from ${{ inputs.tag }} "
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.target }}"
  